version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8080
      KC_PROXY_HEADERS: xforwarded
      KC_HOSTNAME_STRICT: "false"
    ports:
      - "8080:8080"
    networks:
      - plane_dev_env

networks:
  plane_dev_env:
    external: true
